### ISSUE TITLE
Asking for too many permissions

### ISSUE THREAD

**Issue by jyasskin** [GoogleChromeLabs/link-to-text-fragment#11]
IIUC, the extension should be able to do its work by just inspecting the single page on which I've clicked its context menu item, but when I click that context menu item in Chrome, it asks to "Read and change all your data on the websites you visit."

**Comment by tomayac** [comment]
This is caused by [this line in the manifest](https://github.com/GoogleChromeLabs/link-to-text-fragment/blob/1966519aeb79bb342319e427c82c90ff465b06a9/manifest.json#L11) which is required for polyfilling Text Fragment for Firefox and Safari, but also browsers like Brave that do not implement or expose the feature. The check for native support needs to be updated since `Location.prototype.fragmentDirective` is not there anymore. I have a fix up soon.
