### ISSUE TITLE
Jumps away from link-to-text link

### ISSUE THREAD

**Issue by CAPS808** [GoogleChromeLabs/link-to-text-fragment#21]
I'm attempting to link jump for citation purposes on the government cdc website.  I use the link-to-text app on chrome and paste it appropriately but it will jump to my desired highlighted text and then jump to the top of the page quickly thereafter.

**Comment by tomayac** [comment]
Would you have an example link for me to reproduce the behavior?

**Comment by CAPS808** [comment]
Yes thank you.

https://www.cdc.gov/coronavirus/2019-ncov/community/schools-childcare/schools.html#anchor_1589932092921:~:text=Make%20sure%20that%20staff%20and%20families%20know%20that

[image: CDC Webpage example.jpg]

**Comment by tomayac** [comment]
It loaded correctly for me, albeit I noticed some minor content jumps on desktop, which may be more disturbing on a smaller viewport on mobile. These are due to images or videos (or ads) not communicating their final dimensions to the page. If you have anything to do with CDC, this is the [recommendation](https://web.dev/optimize-cls/#images-without-dimensions) to fix this.

<img width="1792" alt="Screen Shot 2020-10-26 at 09 31 55" src="https://user-images.githubusercontent.com/145676/97150265-29334780-176e-11eb-865e-60820f1cb25c.png">
