### ISSUE TITLE
Fragment link not working

### ISSUE THREAD

**Issue by spottedmahn** [GoogleChromeLabs/link-to-text-fragment#24]
The following link isn't working: https://tools.ietf.org/html/rfc6125#page-44:~:text=E.g.%20*.bar.com%20would%20match%20a.bar.com

text fragment: `E.g. *.bar.com would match a.bar.com`

**Screenshot:**
![image](https://user-images.githubusercontent.com/14079228/98996550-07251d80-2501-11eb-87a3-1b72b6272033.png)

---

this link seems to work: https://tools.ietf.org/html/rfc6125#page-44:~:text=more%20than%20one%20dNSName%20name,-)%2C

---

I'm thinking the special characters are the difference.  Is this a Chrome issue?

**Comment by tomayac** [comment]
Good news! I have tried your [link](https://tools.ietf.org/html/rfc6125#page-44:~:text=E.g.%20*.bar.com%20would%20match%20a.bar.com) in Chrome Version 87.0.4280.47 (Official Build) beta (x86_64). If there was a problem in earlier versions, it is fixed by now.
 
<img width="675" alt="Screen Shot 2020-11-13 at 09 04 07" src="https://user-images.githubusercontent.com/145676/99043913-3aae8900-258f-11eb-864f-18ceea0f2e12.png">

**Comment by spottedmahn** [comment]
Nice, I'll try again, thanks!  The behavior was **inconsistent** I noticed after future tests.

For example, I just tried that [link ](https://tools.ietf.org/html/rfc6125#page-44:~:text=E.g.%20*.bar.com%20would%20match%20a.bar.com)and it worked this time 🤷‍♂️

Chrome version for reference:

![image](https://user-images.githubusercontent.com/14079228/99082032-a1cd3d00-2591-11eb-96e9-2e115babf8ec.png)

**Comment by tomayac** [comment]
Seemingly inconsistent behavior is almost certainly due to [security constraints](https://web.dev/text-fragments/#security:~:text=Text%20fragment%20directives%20are%20invoked%20only,result%20of%20a%20user%20activation.). But glad it works now.
