### ISSUE TITLE
Text Fragment Links Not Working From Google Sheets Cell

### ISSUE THREAD

**Issue by obrien79** [GoogleChromeLabs/link-to-text-fragment#35]
Unable to use chrome extension to link **from a google sheet cell** to a **text fragment in a google support page** 

![image](https://user-images.githubusercontent.com/83428578/116612939-f7ea2e80-a8ec-11eb-9188-7fff1aed25e0.png)

**Comment by bokand** [comment]
Do you mean that the link doesn't work when clicked from sheets? Does it work when pasted in the URL bar? Can you share the link that's not working?

**Comment by tomayac** [comment]
Not sure what the problem is. I could get it working in this [sheet](https://docs.google.com/spreadsheets/d/1nvoNsXfLvnHupq8pWwi8vBFAs5hwRbPFnHkc8wJR4Rg/edit?usp=sharing) using the `HYPERLINK()` function.

**Comment by obrien79** [comment]
I was trying to enter link using cmd + k and the text fragment url, didn't work then. Also the main point is it wasn't working specifically when deep linking to a section within a Google support page. [Example](https://docs.google.com/spreadsheets/d/1wpvmqYVI6IPzTNIGafYLNNo9fIuDZWgK1H8m2qlDY88/edit?usp=sharing)

**Comment by bokand** [comment]
Ah, thanks for the example - that's interesting, I don't see any obvious reason why it wouldn't work. I'll take a look.

**Comment by tomayac** [comment]
Ah, so the problem is not with the link generation (what the extension does), but with the link matching (what Chrome does). I can reproduce the link to not work, but only sometimes. @bokand (who works on the Chrome part) said he's taking a look. I (as the one who works on the extension) will leave the issue closed. Maybe @bokand can share the resolution or a bug ID for you to subscribe to here (commenting always works, even if the Issue is closed).

**Comment by bokand** [comment]
Sorry for the delay - I did take a look. It seems the page is doing dynamic loading so in cases where it doesn't work it's because the page issues the `load` event but it's still actually inserting content into the DOM. I can make it work fairly reliably when opening in an incognito window but subsequent loads reproduce the issue and fail to scroll-to the text. I'm guessing the page does some kind of cached retrieval.

https://crbug.com/963045 is the chromium bug tracking issues like this.
