### ISSUE TITLE
Show toast/notification message for success or failed to make text link fragment.

### ISSUE THREAD

**Issue by sobujbd** [GoogleChromeLabs/link-to-text-fragment#4]
**Link To Text Fragment** will be new chapter for Web Browser, I think. Thanks for thought out such of things.

I don't know, how user will take to see success or failed toast/notification message while they're copy link for **Text Highlighting** through **Link to Text Fragment**.

But I saw, some of websites not working to make text highlighting link through **LTTF**. Example website : Chrome Webstore.

**Comment by tomayac** [comment]
> **Link To Text Fragment** will be new chapter for Web Browser, I think. Thanks for thought out such of things.

Happy you like the feature!

> I don't know, how user will take to see success or failed toast/notification message while they're copy link for **Text Highlighting** through **Link to Text Fragment**.

It will flash yellow if the link creation has succeeded, and show an alert when it hasn't.

> But I saw, some of websites not working to make text highlighting link through **LTTF**. Example website : Chrome Webstore.

Extensions generally don't run on the Chrome Web Store, since this would be a security issue. There are other hosts that can be blocked, unfortunately, currently there is no way for an extension to know about the fact that it's blocked. This is tracked in https://crbug.com/1093264. Please subscribe (click the star icon) to this bug instead, I'm closing the present Issue.
