### ISSUE TITLE
Generate URL Strips Part of the Original URL

### ISSUE THREAD

**Issue by YisroelTech** [GoogleChromeLabs/link-to-text-fragment#5]
I was on this page `https://www.ivelt.com/forum/viewtopic.php?p=2245310` and used the extension to generate a link and it generated the following, which is not a working link to the page: `https://www.ivelt.com/forum/viewtopic.php#post_content2244975:~:text=%D7%91%D7%90%D7%96%D7%95%D7%A0%D7%93%D7%A2%D7%A8%D7%A2`.

Why doesn't it leave the `?p=2245310` part of the original URL (like `https://www.ivelt.com/forum/viewtopic.php?p=2245310#post_content2244975:~:text=%D7%91%D7%90%D7%96%D7%95%D7%A0%D7%93%D7%A2%D7%A8%D7%A2`) which would be a working link to text fragment?

**Comment by tomayac** [comment]
This is a problem that was fixed in version 1.1.10 of the extension, but sorry for the inconvenience this caused you now. Please verify that this is the version you are on. The simplest way to force the latest version to be installed is by uninstalling and then reinstalling the extension. Please comment again should this problem still occur. For now, I close the Issue.

**Comment by YisroelTech** [comment]
I had version 1.1.9, I updated (forced an Update with the Update button in the extension settings when Developer Mode is On) to version 1.1.10 and it all good now.

Thanks!

**Comment by tomayac** [comment]
Perfect, thanks for letting me know, and apologies for the bug again.
