### ISSUE TITLE
Unable to link to text

### ISSUE THREAD

**Issue by DIYdee** [GoogleChromeLabs/link-to-text-fragment#50]
I have tried multiple times, but when I create a link to text the URL only goes to the page and not the text.

Is there some way to fix this?

**Comment by Mike-B2021** [comment]
I do not get this issue on **most** websites.

However can you try:

1 Go to https://www.bbc.co.uk/news
2 Choose an article and open it in the same or a new tab (shouldn't matter)
I chose a link which opened  into this article https://www.bbc.co.uk/news/health-59909860  
I see this (Capture 1)
![Capture 1](https://user-images.githubusercontent.com/92262114/148647956-2907cf76-3222-476f-bfaa-ba89a0deeb3c.JPG)
3 copy the link and pasted it into a word doc - see the attached "Link test" doc, Test 1 containing the link which opens into the **page** as expected
Scroll down the page to the required area of text, highlight an are of text, repeat the right-click and, **as you say** the resulting link goes to the page, **NOT** the text.

4 Repeat the above on **THIS** website https://theconversation.com/supply-chains-in-2022-shortages-will-continue-but-for-some-sellers-the-problem-will-be-too-much-stock-174085, again choosing an area of text.
You will find that on this website the resulting link opens at the required area of text within the page 

See the attached "Link test" doc, Test 2 containing the link which opens into the area of text.
[Link test.docx](https://github.com/GoogleChromeLabs/link-to-text-fragment/files/7833395/Link.test.docx)

I repeated the above on several sites and most behaved as required.

From all this I deduce that it is the coding of certain websites that allow / disallow "Link to Selected Text" to select certain areas, rather than a problem with the Extension itself. 
Doesn't fix it but IMO, shows that it's not a problem with the actual Extension.

**Comment by tomayac** [comment]
Thanks for putting together these tests. The generated links from the extension are correct. Could I ask you to file Chromium browser bugs for the ones that don't work? You can do so via [new.crbug.com](https://new.crbug.com/). Choose `Blink>Scroll` in the **component** field. Thank you!

**Comment by Mike-B2021** [comment]
@tomayac That would be very difficult as it **appears** to be random sites, i.e. from above BBC News exhibits the issue, The Conversation does not.
Clearly it's not random, rather it's something in how these sites are coded and i confess to not knowing enough about coding to analyse that

**Comment by tomayac** [comment]
Since the BBC (probably) uses templates for their sites, a representative example of each problem would suffice. A common issue is changes on the site, either to the [actual text](https://web.dev/text-fragments/#textstart-and-textend), or the [surrounding prefixes and/or suffixes](https://web.dev/text-fragments/#prefix-and-suffix) that the extension uses to make the links unique. 

In simplified language, if you wanted to link to a specific instance of, say, the word "the", there would need to be a way to say which "the", since there are many "the"s on a typical English page. The extension then tries to find a unique occurrence, for example, the one "the" that is immediately followed by the word "example". If this word happens to change, the whole link doesn't work anymore. In the worst case, the word happens to be a dynamically changing word that changes for almost each load. There is no way for the extension to detect this.

**Comment by Mike-B2021** [comment]
Exactly - I follow that explanation - thanks.
There may be many more examples that neither of us has yet thought of, but what you seem to be saying is this extension can never be "all things to all men" which is just how it is.

As the list will never be complete, someone would need to go through dozens of websites to get a cross-section - I am **not** volunteering for that task - sorry! :-)

I would respectfully suggest creating a bug that simply points at this one would be the most one could **usefully** do.

Would seem to me that creating a new bug is pointless; rather this issue should go into Release Notes as a warning about a limitation of  the extension.

**Comment by tomayac** [comment]
It's not a limitation of the extension, but of the feature per se, since it's based on live web pages and not archives. If you want to be sure a link works "forever", you can actually [archive a page](https://web.archive.org/) first, and then link to the archived version (example: https://web.archive.org/web/20220110093302/https://www.bbc.com/news/health-59909860#:~:text=is%20this%20nhs%20crisis%20really%20worse%20than%20ones%20before%3F).

**Comment by Mike-B2021** [comment]
Which would be pretty pointless for most users I suggest.

So in practical (User) terms it's a (perceived) limitation because the extension may not work **as desired** on live web pages, but is working **as intended** by the Dev.

Once again to be mentioned in Release Notes rather than considered as a bug, IMO
