### ISSUE TITLE
German Umlauts Support

### ISSUE THREAD

**Issue by JanEickholt** [GoogleChromeLabs/link-to-text-fragment#53]
Hey, 
I noticed, that the addon doesn't really support german umlauts and wanted to ask if it's possible to add them (ä,ö,ü).
Would really appreciate it, because it would make some link creations easier.

Encodings that are missing atm:
Ä = %C3%84
Ö = %C3%96
Ü = %C3%9C
ä = %C3%A4
ö = %C3%B6
ü = %C3%BC

**Comment by tomayac** [comment]
Umlauts are not really required by the spec, since the comparison works at the base level ([spec deep link](https://wicg.github.io/scroll-to-text-fragment/#:~:text=Set%20matchIndex%20to,and%20other%20marks.)), and links just work without umlauts [example](https://www.tagesschau.de/ausland/europa/ukraine-russland-verhandlungen-101.html#:~:text=Die-,gesprache,-zwischen%20der%20Ukraine).
