### ISSUE TITLE
Link to text doesn't work in websites translated into another languages.

### ISSUE THREAD

**Issue by JabSYsEmb** [GoogleChromeLabs/link-to-text-fragment#61]
issue; I tried to link to a text after translating a website from Japanese to english but the extension links to the translated version of the text instead of the origin text, Japanese version.
 
Is there any way to make the extension link to the origin text in case the website was translated into another languages or makes links correctly to translated text directly ?
![out](https://user-images.githubusercontent.com/32222578/163280871-6f47e14f-127b-4689-94ad-0b849364bfd1.gif)

**Comment by bokand** [comment]
I'm afraid not - the translation actually changes the content on the page so the extension (and the Chrome built-in feature)  it doesn't know whether the highlighted text is translated or not and what the source text was; you'd have to create the link from the original page.

**Comment by JabSYsEmb** [comment]
I agree it may be tricky to figure out if the highlighted text is the source text or not, but wouldn't inspecting requests help us figure out if a page has been translated or not? For instance, in the aforementioned issue if we had inspected the network tab  in chrome dev tools we would've seen a request made to translate.googleapis.com 
```
Request URL: https://translate.googleapis.com/_/translate_http/_/js/k=translate_http.tr.en_US.pWhPTwXxHvM.O/am=Ag/d=1/exm=el_conf/ed=1/rs=AN8SPfrLUEjuflo2aG8o_zzUnNGgVGR0fw/m=el_main
Request Method: GET
Status Code: 200  (from disk cache)
Remote Address: 172.217.17.106:443
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by bokand** [comment]
Yeah, I mean, it's not technically impossible but likely difficult to get right and more work than can be justified by usage.

Realizing the page is translated is probably not too hard, and maybe we just disable creating the link in that case to prevent confusion. But I'm not sure how you'd go from a translated selection snippet back to the untranslated text it represents...translating back to the original language doesn't guarantee the original text.

What I *think* might be interesting is a translate fragment directive, so that the link could contain the fact that it's to the translated page: `example.com#:~:translate=en-ca&text=the%20translated%20text` so that the link would always land on the translated page (and then the scroll-to-text bit would work).

However, that's a new web platform feature - well outside the scope of this extension.

**Comment by tomayac** [comment]
Closing as per the arguments brought up in the discussion above. Thanks both!
