### ISSUE TITLE
Persistent error

### ISSUE THREAD

**Issue by thpdx** [GoogleChromeLabs/link-to-text-fragment#8]
I'm getting an error anytime I try to use the [Link to Text Fragment](https://chrome.google.com/webstore/detail/link-to-text-fragment/pbcodcjpfjdpcineamnnmbkkmkdpajjg) extension in Chrome.

No matter how much text I select, I always get this error:
<img width="1356" alt="Screen Shot 2020-07-30 at 11 52 06 AM" src="https://user-images.githubusercontent.com/69013158/88962303-1a1a2780-d25b-11ea-8661-5ea15d2db113.png">

Can you help me understand what I'm doing wrong?

**Comment by bokand** [comment]
I'm able to reproduce this. It happens when I start the selection from below the block of text. It doesn't occur when I select from the right of the end of the text.

When it happens we get an exception in `getText` as we assume `focusNode` is a text node but in this case it's an element (the container for the next search result) so there is no `data` member.

I'm not familiar enough with the code to know what the expectation is but @tomayac would know more.

**Comment by tomayac** [comment]
Thanks for the bug report. I have a fix coming and will update this thread once it lands.

**Comment by tomayac** [comment]
This issue has been fixed. I have pushed a new version of the extension to the stores. Pending approval, it should auto-update on your browser soon.  Thanks again for the report!
