### ISSUE TITLE
Copy Exact Link to Selected Text

### ISSUE THREAD

**Issue by mfulton26** [GoogleChromeLabs/link-to-text-fragment#9]
I'd like the URL to contain the full quote of the text from the page. As such, instead of generating a URL using both `textStart` and `textEnd` I would like an option to copy a URL for an ["exact" search](https://wicg.github.io/scroll-to-text-fragment/#ref-for-concept-range①⓪:~:text=%22exact%22%20search) (using `textStart` only and leaving `textEnd` undefined).

This way I can decode the URL to get the full quotation without visiting the site, it also will invalidate the URL (which sometimes I want) if the text on the page changes and I still know what the site said when the URL was previously generated.

I propose adding another context menu option in addition to the existing "Copy Link to Selected Text", perhaps captioned as "Copy Exact Link to Selected Text".

**Comment by tomayac** [comment]
While the spec does recommend to prefer exact searches over context-based searches, it also [recommends](https://wicg.github.io/scroll-to-text-fragment/#example-53e82e58:~:text=It%20is%20recommended%20that%20text%20snippets,the%20string%20as%20a%20range%2Dbased%20match.) that *"[a]bove this limit [of 300 characters], the UA should encode the string as a range-based match"*. In the extension, currently, for the sake of shorter URLs, we [experiment with 100 characters](https://github.com/GoogleChromeLabs/link-to-text-fragment/blob/72b9b33e98ee9412ba789eb8e0d19cd997b8d8fb/background_script.js#L21), and it seems to work well enough.

The majority of use cases, unlike yours, aims at being resistant to minor text changes. Adding a second context menu entry is not desirable, since it would confuse most users.

My suggestion would be to clone the code from the GitHub repository, make the change to bump the limit to >=300 characters, and install the extension locally:

1. Open the Extension Management page by navigating to `chrome://extensions`.
1. Enable Developer Mode by clicking the toggle switch next to *Developer mode*.
1. Click the *LOAD UNPACKED* button and select the cloned extension directory.

**Comment by mfulton26** [comment]
Before I go create a new extension I had an idea:

What about setting up an extension option to set the number of characters threshold to transition from exact searched to context-based ones?

It could default to 100 and could be set to as low as 0 to basically disable exact searches (assuming that's applicable here) and could have no real max value but if someone sets it to something greater than or equal to 300 then they get a warning message explaining the situation.

For my use case I think I wouldn't need more than 300 characters so maybe the option is limited to that but I'm not sure it's really necessary to limit it to less than 300 either.

Thank you.

**Comment by tomayac** [comment]
I understand the desire to have such a setting, but since it's a power user feature that makes providing help to regular users harder (since you never know what they changed), I am very reluctant to add this.

Instead, I encourage you to just clone the extension and make your adjustments, it's all Apache 2.0 licensed, it's completely OK to even release your clone on the Chrome Web Store.
