### ISSUE TITLE
Does not work on the United Nations Code for Trade and Transport Locations location list.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [GoogleChromeLabs/link-to-text-fragment#98]
Activating it via the toolbar or context menu on https://service.unece.org/trade/locode/gb.htm hangs the tab and does not eventually duplicate a URI into the clipboard. I'm using https://addons.mozilla.org/firefox/downloads/file/3845707/link_to_text_fragment-2.3.2.xpi on https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-122.0-3.2.x86_64.rpm on cpe:/o:opensuse:tumbleweed:20240131.

**Comment by tomayac** [comment]
I fear there's nothing we can do here, since the page is just incredibly large. The built-in feature in the context menu works just fine. The extension traverses the DOM in userland, which is a lot slower, but at least eventually also produces a result, but it does block the tab for a moment indeed. https://service.unece.org/trade/locode/gb.htm#:~:text=Yate-,yate,-GLS

**Comment by RokeJulianLockhart** [comment]
> https://github.com/GoogleChromeLabs/link-to-text-fragment/issues/98#issuecomment-1943395395

@tomayac, by "built-in feature", are you referring to https://support.google.com/chrome/answer/10256233?hl=en-GB&co=GENIE.Platform%3DDesktop&oco=1#:~:text=select%20copy%20link%20to%20highlight? Although I indeed see it using Chrome 124.0.6342.3, it's not available in https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/MozillaFirefox-123.0.1-1.1.x86_64.rpm, so it's not much of a solution. I really fail to see why this isn't even worth tackling with something like a loading bar and button to cancel the operation.
